# site settings
title: OralVision
subtitle:
logo: /assets/favicons/favicon.svg
email: alanchris.rajkumar@gmail.com
description: Utilizing deep learning to revolutionize oral diagnostics<br />in underserved communities.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://akhaled246.github.io/oral-vision/" # the base hostname & protocol for your site
author:
street_address:
city: Frisco
state: TX
zip_code: 75034
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# favicon settings
favicon: /assets/favicons/favicon.ico
favicon_svg: /assets/favicons/favicon.svg
favicon_96x96: /assets/favicons/favicon-96x96.png
favicon_apple_touch: /assets/favicons/apple-touch-icon.png
favicon_manifest: /assets/favicons/site.webmanifest

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
